manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
    - name: halfdane
      url-base: https://github.com
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-input-gestures
      remote: halfdane
      revision: main
      repo-name: zmk-input-gestures
      path: modules/zmk-input-gestures
  self:
    path: config
