# Enable Pointing and Mouse Emulation Frameworks
CONFIG_ZMK_POINTING=y

# Enable Hardware Communication Bus
CONFIG_I2C=y

# Power Management Configuration
CONFIG_ZMK_SLEEP=y
# 15 minutes idle time before deep sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 
